#datasource


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  devtools:
    restart:
      enabled: true

      exclude: test/**
  jackson:
    default-property-inclusion: non_null

  redis:
    host: localhost
    port: 6379
    password:
    database: 0


#spring.devtools.restart.additional-paths: src/main/java


mybatis:
  mapper-locations: classpath*:mybatis-mapper/*Mapper.xml
  #config-location: classpath:mybatis-config.xml

  # aliasesPackage: com.ald.ishangjie.dao.domain,com.ald.ishangjie.web.query
  type-aliases-package: com.example.springboot.dao.domain

person:
  lastName: 好
  age: ${random.int(100)}
  boss: false
  birth: 2008/08/08
  maps: {key1: value1, key2: value2}
#  list:
#    dog
#    cat
#    house
  dog:
    name: 旺财
    age: ${person.age}
  list: dog,cat,house

fbapi:
  shop:
    url: https://ctesth5.51fanbei.com/h5/shop/index.html
server:
  port: 8080
